##########
# collectionbuilder-csv
# Jekyll Digital Collection Generator
# https://github.com/CollectionBuilder/collectionbuilder-csv
##########

##########
# URL VARIABLES
#
# site domain, full URL to the production location of your collection
url: 
# path to location on the domain if necessary e.g. /digital/hjccc
baseurl: 
# location of code, the full url to your github repository
source-code: https://github.com/CollectionBuilder/collectionbuilder-csv

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Descartes Pascal
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: Historic images of rural Iowa
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "The collection includes a subset of 180 glass plate negatives and two tintypes made by Pascal, documenting rural Iowa from the 1890s through the 1910s. Included are family portraits (interior and exterior), family groups, school children, men and women with guns, acrobats, tight rope walkers, several people reenacting a duel, windmills, haystacks, barns, livestock, farmhouses, fields, small town streets, and construction of a school."
# keywords, a short list of subjects describing the collection, separated by semicolon, to appear in rich markup
keywords: iowa;history;agriculture
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: owikle

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the CSV file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: pascal 
# page generation settings [optional!]
# [optional: only used if you need to tweak CB defaults or generate from more than one data file]
# page_gen:
#   - data: 'demo-metadata'
#     template: 'item'
#     name: 'objectid'
#     dir: 'items'
#     extension: 'html' 
#     filter: 'objectid'  

##########
# Site/Organization Branding 
#   Enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#   To remove the branding, comment out these values, or delete them. 
#
organization-name: "Iowa State University Digital Collections"
organization-link: https://digitalcollections.lib.iastate.edu/
organization-logo-banner: https://digitalcollections.lib.iastate.edu/sites/public.uni.dgicloud.com.isu/files/ISU_secondary_red.png
organization-logo-nav: https://digitalcollections.lib.iastate.edu/sites/public.uni.dgicloud.com.isu/files/DClogo3.gif

##########
# GOOGLE SERVICES [optional!]
#
# leave these blank or comment out to NOT include google code
# if present, used to add analytics during "production" build only
# google-analytics-id: "G-XXXXXXXXX"
# google-cse-id: "002151703305773322890:1pu3smhw1t8"

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md, SECURITY.md]
# compress CSS output
sass:
  style: compressed
